config2017 = {
    "coffea": {
        "bkg": "hists_HWW2l2nu_mcbkg_UL17arrays.coffea",
        "sig": "hists_HWW2l2nu_signal_UL17newdata.coffea",
        "data": "hists_HWW2l2nu_data2017arrays.coffea",
        "dy": "hists_HWW2l2nu_dyarrays.coffea",
        "sigjet": "hists_HWW2l2nu_signal_UL17jetarr.coffea",
    },
    "varlist": {
        "ll": {
            "v1": ["lll1_dr", "lll2_dr", "llc_dr"],
            "vtest": [
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "jetflav_btagDeepFlavCvB",
            ],
            "v2": ["ll_pt", "lll1_dr", "lll2_dr", "llc_dr", "lep1_pt", "lep2_pt"],
            "v3": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
            ],
            "v4": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
            ],
            "v5": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v6": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
            ],
            "v7": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "v7t": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "v7_focal": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "v7_focal_dy": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
        },
        "emu": {
            "v7_": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v7_focal": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v7_focal_dy": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v7t": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
        },
    },
    "input_json": {
        "v7t": {
            "ll": "SR_ll_depth3_ntree1000_2017_v7t",
            "emu": "SR_emu_depth3_ntree1000_2017_v7t",
        },
        "v7_focal_dy": {
            "ll": "SR_ll_depth3_ntree500_2017_v7_focal",
            "emu": "SR_emu_depth3_ntree500_2017_v7_focal",
        },
    },
}
