config2017 = {
    "coffea": {
        "bkg": "hists_HWW2l2nu_mcbkg_UL17arrays.coffea",
        "sig": "hists_HWW2l2nu_signal_UL17_4f_arrays.coffea",
        "data": "hists_HWW2l2nu_data2017arrays.coffea",
        "dy": "hists_HWW2l2nu_dyarrays.coffea",
        "sigjet": "hists_HWW2l2nu_signal_UL17jetarr.coffea",
    },
    "coffea_old": {
        "bkg": "hists_HWW2l2nu_mcbkg_UL17arrays.coffea",
        "sig": "hists_HWW2l2nu_signal_UL17newdata.coffea",
        "data": "hists_HWW2l2nu_data2017arrays.coffea",
        "dy": "hists_HWW2l2nu_dyarrays.coffea",
        "sigjet": "hists_HWW2l2nu_signal_UL17jetarr.coffea",
    },
    "coffea_new": {
        "bkg": "../../../coffea_output/hists_HWW2l2nu_mcbkg_UL17_newvar.coffea",
        "sig": "../../../coffea_output/hists_HWW2l2nu_signal_UL17_newvar.coffea",
        "data": "../../../coffea_output/hists_HWW2l2nu_data2017_newvar.coffea",
        "higgs": "../../../coffea_output/hists_HWW2l2nu_higgs_newvars.coffea",
        "dy": "../../../coffea_output/hists_HWW2l2nu_dy_newvar.coffea",
    },
    "varlist": {
        "ll": {
            "gamma": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "dymore": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "wHiggs": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "morevar": [
                "njmet",
                "l1l2_dr",
                "METTkMETdphi",
                "MET_phi",
                "MET_pt",
                "mT1",
                "mT2",
                "mTh",
                "l1met_dphi",
                "l2met_dphi",
                "cmet_dphi",
                "l1c_dr",
                "l2c_dr",
                "l1W1_dphi",
                "l2W1_dphi",
                "l1W2_dphi",
                "l2W2_dphi",
                "metW1_dphi",
                "metW2_dphi",
                "cW1_dphi",
                "cW2_dphi",
                "W1W2_dphi",
                "l1h_dphi",
                "l2h_dphi",
                "W1h_dphi",
                "W2h_dphi",
                "meth_dphi",
                "ch_dphi",
                "lll1_dr",
                "lll2_dr",
                "llmet_dphi",
                "llc_dr",
                "llW1_dphi",
                "llW2_dphi",
                "llh_dphi",
                "jetflav_pt",
                "lep1_pt",
                "lep1_pfRelIso03_all",
                # "dphi_lep1",
                "lep2_pt",
                "lep2_pfRelIso03_all",
                "ll_pt",
                "ll_mass",
                "h_pt",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "nsv",
                "u_par",
                "u_per",
                "tkMET_pt",
                "PuppiMET_pt",
                "MET_ptdivet",
                "MET_proj",
                "TkMET_proj",
                "minMET_proj",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
        },
        "emu": {
            "gamma": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "dymore": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
            "wHiggs": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "morevar": [
                "njmet",
                "l1l2_dr",
                "METTkMETdphi",
                "MET_phi",
                "MET_pt",
                "mT1",
                "mT2",
                "mTh",
                "l1met_dphi",
                "l2met_dphi",
                "cmet_dphi",
                "l1c_dr",
                "l2c_dr",
                "l1W1_dphi",
                "l2W1_dphi",
                "l1W2_dphi",
                "l2W2_dphi",
                "metW1_dphi",
                "metW2_dphi",
                "cW1_dphi",
                "cW2_dphi",
                "W1W2_dphi",
                "l1h_dphi",
                "l2h_dphi",
                "W1h_dphi",
                "W2h_dphi",
                "meth_dphi",
                "ch_dphi",
                "lll1_dr",
                "lll2_dr",
                "llmet_dphi",
                "llc_dr",
                "llW1_dphi",
                "llW2_dphi",
                "llh_dphi",
                "jetflav_pt",
                "lep1_pt",
                "lep1_pfRelIso03_all",
                # "dphi_lep1",
                "lep2_pt",
                "lep2_pfRelIso03_all",
                "ll_pt",
                "ll_mass",
                "h_pt",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "nsv",
                "u_par",
                "u_per",
                "tkMET_pt",
                "PuppiMET_pt",
                "MET_ptdivet",
                "MET_proj",
                "TkMET_proj",
                "minMET_proj",
            ],
        },
    },
    "input_json": {
        "ll": {
            "alpha": "xgb_output/SR_ll_scanalpha_2017_scan.json",
            "dymore": "xgb_output/SR_ll_scangamma_2017_gamma2.json",
            "wHiggs": "xgb_output/SR_ll_scangamma_2017_scan_4f.json",
        },
        "emu": {
            "alpha": "xgb_output/SR_emu_scanalpha_2017_scan.json",
            "dymore": "xgb_output/SR_emu_scangamma_2017_gamma2.json",
            "wHiggs": "xgb_output/SR_emu_scangamma_2017_scan_4f.json",
        },
    },
}
