config2017 = {
    "coffea": {
        
        "bkg": "hists_HWW2l2nu_mcbkg_UL17arrays.coffea",
        "sig": "hists_HWW2l2nu_signal_UL17_4f_arrays.coffea",
        "data": "hists_HWW2l2nu_data2017arrays.coffea",
        "dy": "hists_HWW2l2nu_dyarrays.coffea",
        "sigjet": "hists_HWW2l2nu_signal_UL17jetarr.coffea",
    },

    "coffea_old": {
        
        "bkg": "hists_HWW2l2nu_mcbkg_UL17arrays.coffea",
        "sig": "hists_HWW2l2nu_signal_UL17newdata.coffea",
        "data": "hists_HWW2l2nu_data2017arrays.coffea",
        "dy": "hists_HWW2l2nu_dyarrays.coffea",
        "sigjet": "hists_HWW2l2nu_signal_UL17jetarr.coffea",
    },
    "varlist": {
        "ll": {
            "v1": ["lll1_dr", "lll2_dr", "llc_dr"],
            "vtest": [
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "jetflav_btagDeepFlavCvB",
            ],
            "v2": ["ll_pt", "lll1_dr", "lll2_dr", "llc_dr", "lep1_pt", "lep2_pt"],
            "v3": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
            ],
            "v4": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
            ],
            "v5": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v6": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
            ],
            "v7": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "v7t": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "alpha": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "gamma2": [
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "alpha_morevar": [
                
                "ll_pt",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "lep1_pt",
                "lep2_pt",
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "l1met_dphi",
                "l2met_dphi",
                "llmet_dphi",
                "cW1_dphi",
                "npv",
                "nsv",
                "mT1",
                "mT2",
                "u_par",
                "u_per",
                "h_pt",
                "TkMET_pt",
                "PuppiMET_pt",
                "MET_ptdivet",
                "MET_proj",
                "TkMET_proj",
                "minMET_proj",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
        },
        "emu": {
            "v7_": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v7_focal": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "v7_focal_dy": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "gamma2": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "alpha": [
                "ll_mass",
                "MET_pt",
                "jetflav_pt",
                "lep1_pt",
                "lep2_pt",
                "ll_pt",
                "mT1",
                "mT2",
                "jetflav_btagDeepFlavCvL",
                "jetflav_btagDeepFlavCvB",
                "lll1_dr",
                "lll2_dr",
                "llc_dr",
                "l1met_dphi",
                "l2met_dphi",
                "cW1_dphi",
            ],
            "jet": [
                "nj",
                "jetmetdphi",
                "jetpt",
                "jeteta",
                "jetphi",
                "jetlepdr",
                "jetCvL",
                "jetCvB",
            ],
        },
    },
    "input_json": {
        "ll": {
            "alpha":"xgb_output/SR_ll_scanalpha_2017_scan.json",
            "gamma":"xgb_output/SR_ll_scangamma_2017_scan.json",
            "gamma2":"SR_ll_scangammas_2017_scan_4f.json"
        },
        "emu":{
            "alpha": "xgb_output/SR_emu_scanalpha_2017_scan.json",
            "gamma": "xgb_output/SR_emu_scangamma_2017_scan.json",
           "gamma2":"SR_emu_scangammas_2017_scan_4f.json"
        }
    }
    
}
